services:
  postgres16:
    container_name: 'postgres16'
    image: postgres:16-alpine
    ports: 
      - '127.0.0.1:5432:5432'
    volumes:
      - ./pg_data/pg_data_16:/var/lib/postgresql/data/
      - ./src/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      POSTGRES_DB: puzzlehunt_bot
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres